image: node:latest

stages:
    - build
    - test

cache:
    paths:
        - node_modules/

install_deps:
    stage: build
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/

test:
    stage: test
    script:
        - npm test
